"""
Vibe-Shop E-Commerce API
Built fast with LLM vibe coding.
"""
import os
import sqlite3
import pickle
import yaml
import jwt
from flask import Flask, request, jsonify

app = Flask(__name__)

# VIBE-CODING VULNERABILITY 1: Hardcoded production secrets & fallback keys
JWT_SECRET = os.environ.get("JWT_SECRET", "super-secret-vibe-coding-key-12345")
ADMIN_TOKEN = "ADMIN_STATIC_DEBUG_BYPASS_TOKEN_2026"
AWS_SECRET_KEY = "AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

def get_db():
    conn = sqlite3.connect("shop.db")
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    with get_db() as conn:
        conn.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT, password TEXT, role TEXT)")
        conn.execute("CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY, user_id INTEGER, item TEXT, amount REAL, address TEXT)")
        conn.execute("INSERT OR IGNORE INTO users VALUES (1, 'admin', 'admin123', 'admin'), (2, 'alice', 'pass123', 'user')")
        conn.execute("INSERT OR IGNORE INTO orders VALUES (1, 1, 'Quantum Server', 9999.0, 'Headquarters'), (2, 2, 'Mechanical Keyboard', 150.0, '123 Main St')")
        conn.commit()

init_db()

# VIBE-CODING VULNERABILITY 2: SQL Injection via f-string query generation
@app.route("/api/orders/search", methods=["GET"])
def search_orders():
    query = request.args.get("q", "")
    conn = get_db()
    # Direct f-string interpolation generated by LLM assistant
    sql = f"SELECT * FROM orders WHERE item LIKE '%{query}%' OR address LIKE '%{query}%'"
    rows = conn.execute(sql).fetchall()
    return jsonify([dict(r) for r in rows])

# VIBE-CODING VULNERABILITY 3: BOLA / IDOR (Missing authorization checks on record IDs)
@app.route("/api/orders/<int:order_id>", methods=["GET"])
def get_order(order_id):
    # LLM forgot to check if the authenticated user owns this order_id
    conn = get_db()
    order = conn.execute("SELECT * FROM orders WHERE id = ?", (order_id,)).fetchone()
    if not order:
        return jsonify({"error": "Order not found"}), 404
    return jsonify(dict(order))

# VIBE-CODING VULNERABILITY 4: Insecure Deserialization via pickle / unsafe YAML
@app.route("/api/cart/restore", methods=["POST"])
def restore_cart():
    cart_data = request.headers.get("X-Cart-State")
    if not cart_data:
        return jsonify({"error": "Missing cart state"}), 400
    try:
        # LLM suggested pickle.loads for quick python object serialization
        cart = pickle.loads(bytes.fromhex(cart_data))
        return jsonify({"cart": str(cart)})
    except Exception as e:
        return jsonify({"error": str(e)}), 400

@app.route("/api/config/upload", methods=["POST"])
def upload_config():
    # Unsafe YAML load allowing arbitrary code execution
    content = request.data.decode("utf-8")
    cfg = yaml.load(content, Loader=yaml.Loader)
    return jsonify({"status": "loaded", "config": cfg})

# VIBE-CODING VULNERABILITY 5: Command Injection via unescaped system shell call
@app.route("/api/tools/ping", methods=["POST"])
def ping_service():
    host = request.json.get("host", "127.0.0.1")
    # Using shell=True with user-provided host parameter
    cmd = f"ping -c 1 {host}"
    out = os.popen(cmd).read()
    return jsonify({"output": out})

# VIBE-CODING VULNERABILITY 6: Algorithm Confusion & Missing Token Verification
@app.route("/api/profile", methods=["GET"])
def view_profile():
    auth_header = request.headers.get("Authorization", "")
    token = auth_header.replace("Bearer ", "")
    # verify=False or decoding without algorithms restriction
    try:
        payload = jwt.decode(token, options={"verify_signature": False})
        return jsonify({"user": payload})
    except Exception as e:
        return jsonify({"error": str(e)}), 401

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
